# Theme and Plugins
remote_theme: pages-themes/midnight@v0.2.0
plugins:
 - jekyll-remote-theme
# Repository Metadata
title: "NBA MVP Dashboard"
description: "A data-driven Power BI dashboard analyzing MVP performances across NBA history."
author: "Aeron Abrahan"
github_username: "aeronabrahan"
# Navigation Settings
show_downloads: true
include:
 - README.md
 - assets/
# Repository Settings
repository: "aeronabrahan/nba-mvp-dashboard"
url: "https://github.com/aeronabrahan/nba-mvp-dashboard"
# SEO and Social Sharing
social:
 name: "Aeron Abrahan"
 links:
   - "https://github.com/aeronabrahan"
   - "https://linkedin.com/in/jagabrahan"
# Custom Options
markdown: kramdown
permalink: pretty
